using Toybox.WatchUi;
class CurvedFonts {
    static function getFont(idx) {
        if (idx == 0) { return WatchUi.loadResource(Rez.Fonts.curved_0); }
        else if (idx == 1) { return WatchUi.loadResource(Rez.Fonts.curved_1); }
        else if (idx == 2) { return WatchUi.loadResource(Rez.Fonts.curved_2); }
        else if (idx == 3) { return WatchUi.loadResource(Rez.Fonts.curved_3); }
        else if (idx == 4) { return WatchUi.loadResource(Rez.Fonts.curved_4); }
        else if (idx == 5) { return WatchUi.loadResource(Rez.Fonts.curved_5); }
        else if (idx == 6) { return WatchUi.loadResource(Rez.Fonts.curved_6); }
        else if (idx == 7) { return WatchUi.loadResource(Rez.Fonts.curved_7); }
        else if (idx == 8) { return WatchUi.loadResource(Rez.Fonts.curved_8); }
        else if (idx == 9) { return WatchUi.loadResource(Rez.Fonts.curved_9); }
        else if (idx == 10) { return WatchUi.loadResource(Rez.Fonts.curved_10); }
        else if (idx == 11) { return WatchUi.loadResource(Rez.Fonts.curved_11); }
        else if (idx == 12) { return WatchUi.loadResource(Rez.Fonts.curved_12); }
        else if (idx == 13) { return WatchUi.loadResource(Rez.Fonts.curved_13); }
        else if (idx == 14) { return WatchUi.loadResource(Rez.Fonts.curved_14); }
        else if (idx == 15) { return WatchUi.loadResource(Rez.Fonts.curved_15); }
        else if (idx == 16) { return WatchUi.loadResource(Rez.Fonts.curved_16); }
        else if (idx == 17) { return WatchUi.loadResource(Rez.Fonts.curved_17); }
        else if (idx == 18) { return WatchUi.loadResource(Rez.Fonts.curved_18); }
        else if (idx == 19) { return WatchUi.loadResource(Rez.Fonts.curved_19); }
        else if (idx == 20) { return WatchUi.loadResource(Rez.Fonts.curved_20); }
        else if (idx == 21) { return WatchUi.loadResource(Rez.Fonts.curved_21); }
        else if (idx == 22) { return WatchUi.loadResource(Rez.Fonts.curved_22); }
        else if (idx == 23) { return WatchUi.loadResource(Rez.Fonts.curved_23); }
        else if (idx == 24) { return WatchUi.loadResource(Rez.Fonts.curved_24); }
        else if (idx == 25) { return WatchUi.loadResource(Rez.Fonts.curved_25); }
        else if (idx == 26) { return WatchUi.loadResource(Rez.Fonts.curved_26); }
        else if (idx == 27) { return WatchUi.loadResource(Rez.Fonts.curved_27); }
        else if (idx == 28) { return WatchUi.loadResource(Rez.Fonts.curved_28); }
        else if (idx == 29) { return WatchUi.loadResource(Rez.Fonts.curved_29); }
        else if (idx == 30) { return WatchUi.loadResource(Rez.Fonts.curved_30); }
        else if (idx == 31) { return WatchUi.loadResource(Rez.Fonts.curved_31); }
        else if (idx == 32) { return WatchUi.loadResource(Rez.Fonts.curved_32); }
        else if (idx == 33) { return WatchUi.loadResource(Rez.Fonts.curved_33); }
        else if (idx == 34) { return WatchUi.loadResource(Rez.Fonts.curved_34); }
        else if (idx == 35) { return WatchUi.loadResource(Rez.Fonts.curved_35); }
        else if (idx == 36) { return WatchUi.loadResource(Rez.Fonts.curved_36); }
        else if (idx == 37) { return WatchUi.loadResource(Rez.Fonts.curved_37); }
        else if (idx == 38) { return WatchUi.loadResource(Rez.Fonts.curved_38); }
        else if (idx == 39) { return WatchUi.loadResource(Rez.Fonts.curved_39); }
        else if (idx == 40) { return WatchUi.loadResource(Rez.Fonts.curved_40); }
        else if (idx == 41) { return WatchUi.loadResource(Rez.Fonts.curved_41); }
        else if (idx == 42) { return WatchUi.loadResource(Rez.Fonts.curved_42); }
        else if (idx == 43) { return WatchUi.loadResource(Rez.Fonts.curved_43); }
        else if (idx == 44) { return WatchUi.loadResource(Rez.Fonts.curved_44); }
        else if (idx == 45) { return WatchUi.loadResource(Rez.Fonts.curved_45); }
        else if (idx == 46) { return WatchUi.loadResource(Rez.Fonts.curved_46); }
        else if (idx == 47) { return WatchUi.loadResource(Rez.Fonts.curved_47); }
        else if (idx == 48) { return WatchUi.loadResource(Rez.Fonts.curved_48); }
        else if (idx == 49) { return WatchUi.loadResource(Rez.Fonts.curved_49); }
        else if (idx == 50) { return WatchUi.loadResource(Rez.Fonts.curved_50); }
        else if (idx == 51) { return WatchUi.loadResource(Rez.Fonts.curved_51); }
        else if (idx == 52) { return WatchUi.loadResource(Rez.Fonts.curved_52); }
        else if (idx == 53) { return WatchUi.loadResource(Rez.Fonts.curved_53); }
        else if (idx == 54) { return WatchUi.loadResource(Rez.Fonts.curved_54); }
        else if (idx == 55) { return WatchUi.loadResource(Rez.Fonts.curved_55); }
        else if (idx == 56) { return WatchUi.loadResource(Rez.Fonts.curved_56); }
        else if (idx == 57) { return WatchUi.loadResource(Rez.Fonts.curved_57); }
        else if (idx == 58) { return WatchUi.loadResource(Rez.Fonts.curved_58); }
        else if (idx == 59) { return WatchUi.loadResource(Rez.Fonts.curved_59); }
        else if (idx == 60) { return WatchUi.loadResource(Rez.Fonts.curved_60); }
        else if (idx == 61) { return WatchUi.loadResource(Rez.Fonts.curved_61); }
        else if (idx == 62) { return WatchUi.loadResource(Rez.Fonts.curved_62); }
        else if (idx == 63) { return WatchUi.loadResource(Rez.Fonts.curved_63); }
        else if (idx == 64) { return WatchUi.loadResource(Rez.Fonts.curved_64); }
        else if (idx == 65) { return WatchUi.loadResource(Rez.Fonts.curved_65); }
        else if (idx == 66) { return WatchUi.loadResource(Rez.Fonts.curved_66); }
        else if (idx == 67) { return WatchUi.loadResource(Rez.Fonts.curved_67); }
        else if (idx == 68) { return WatchUi.loadResource(Rez.Fonts.curved_68); }
        else if (idx == 69) { return WatchUi.loadResource(Rez.Fonts.curved_69); }
        else if (idx == 70) { return WatchUi.loadResource(Rez.Fonts.curved_70); }
        else if (idx == 71) { return WatchUi.loadResource(Rez.Fonts.curved_71); }
        else if (idx == 72) { return WatchUi.loadResource(Rez.Fonts.curved_72); }
        else if (idx == 73) { return WatchUi.loadResource(Rez.Fonts.curved_73); }
        else if (idx == 74) { return WatchUi.loadResource(Rez.Fonts.curved_74); }
        else if (idx == 75) { return WatchUi.loadResource(Rez.Fonts.curved_75); }
        else if (idx == 76) { return WatchUi.loadResource(Rez.Fonts.curved_76); }
        else if (idx == 77) { return WatchUi.loadResource(Rez.Fonts.curved_77); }
        else if (idx == 78) { return WatchUi.loadResource(Rez.Fonts.curved_78); }
        else if (idx == 79) { return WatchUi.loadResource(Rez.Fonts.curved_79); }
        else if (idx == 80) { return WatchUi.loadResource(Rez.Fonts.curved_80); }
        else if (idx == 81) { return WatchUi.loadResource(Rez.Fonts.curved_81); }
        else if (idx == 82) { return WatchUi.loadResource(Rez.Fonts.curved_82); }
        else if (idx == 83) { return WatchUi.loadResource(Rez.Fonts.curved_83); }
        else if (idx == 84) { return WatchUi.loadResource(Rez.Fonts.curved_84); }
        else if (idx == 85) { return WatchUi.loadResource(Rez.Fonts.curved_85); }
        else if (idx == 86) { return WatchUi.loadResource(Rez.Fonts.curved_86); }
        else if (idx == 87) { return WatchUi.loadResource(Rez.Fonts.curved_87); }
        else if (idx == 88) { return WatchUi.loadResource(Rez.Fonts.curved_88); }
        else if (idx == 89) { return WatchUi.loadResource(Rez.Fonts.curved_89); }
        else if (idx == 90) { return WatchUi.loadResource(Rez.Fonts.curved_90); }
        else if (idx == 91) { return WatchUi.loadResource(Rez.Fonts.curved_91); }
        else if (idx == 92) { return WatchUi.loadResource(Rez.Fonts.curved_92); }
        else if (idx == 93) { return WatchUi.loadResource(Rez.Fonts.curved_93); }
        else if (idx == 94) { return WatchUi.loadResource(Rez.Fonts.curved_94); }
        else if (idx == 95) { return WatchUi.loadResource(Rez.Fonts.curved_95); }
        else if (idx == 96) { return WatchUi.loadResource(Rez.Fonts.curved_96); }
        else if (idx == 97) { return WatchUi.loadResource(Rez.Fonts.curved_97); }
        else if (idx == 98) { return WatchUi.loadResource(Rez.Fonts.curved_98); }
        else if (idx == 99) { return WatchUi.loadResource(Rez.Fonts.curved_99); }
        else if (idx == 100) { return WatchUi.loadResource(Rez.Fonts.curved_100); }
        else if (idx == 101) { return WatchUi.loadResource(Rez.Fonts.curved_101); }
        else if (idx == 102) { return WatchUi.loadResource(Rez.Fonts.curved_102); }
        else if (idx == 103) { return WatchUi.loadResource(Rez.Fonts.curved_103); }
        else if (idx == 104) { return WatchUi.loadResource(Rez.Fonts.curved_104); }
        else if (idx == 105) { return WatchUi.loadResource(Rez.Fonts.curved_105); }
        else if (idx == 106) { return WatchUi.loadResource(Rez.Fonts.curved_106); }
        else if (idx == 107) { return WatchUi.loadResource(Rez.Fonts.curved_107); }
        else if (idx == 108) { return WatchUi.loadResource(Rez.Fonts.curved_108); }
        else if (idx == 109) { return WatchUi.loadResource(Rez.Fonts.curved_109); }
        else if (idx == 110) { return WatchUi.loadResource(Rez.Fonts.curved_110); }
        else if (idx == 111) { return WatchUi.loadResource(Rez.Fonts.curved_111); }
        else if (idx == 112) { return WatchUi.loadResource(Rez.Fonts.curved_112); }
        else if (idx == 113) { return WatchUi.loadResource(Rez.Fonts.curved_113); }
        else if (idx == 114) { return WatchUi.loadResource(Rez.Fonts.curved_114); }
        else if (idx == 115) { return WatchUi.loadResource(Rez.Fonts.curved_115); }
        else if (idx == 116) { return WatchUi.loadResource(Rez.Fonts.curved_116); }
        else if (idx == 117) { return WatchUi.loadResource(Rez.Fonts.curved_117); }
        else if (idx == 118) { return WatchUi.loadResource(Rez.Fonts.curved_118); }
        else if (idx == 119) { return WatchUi.loadResource(Rez.Fonts.curved_119); }
        return null;
    }
}
